
services:
  workspace:
    build: .
    volumes:
      - ../..:/workspaces:delegated
      
    depends_on:
      - mongodb


  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data-configdb:/data/configdb
    env_file:
      - .env
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongodb-data-configdb:
